ANDROID: fs: Export free_fs_struct and set_fs_pwd
allmodconfig builds fail with:

ERROR: "free_fs_struct" undefined!
ERROR: "set_fs_pwd" undefined!

Export the missing symbols.

Change-Id: I4877ead19d7e7f0c93d4c4cad5681364284323aa
Fixes: 0ec03f845799 ("ANDROID: sdcardfs: override umask on mkdir and create")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 1cd3d347147bee1b8a3fb7624ab23eb3bdcece41)
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>